<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Arjun Pawar (arjun7@stanford.edu)">

<title>Linear Regression Lab</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="RegressionLab_files/libs/clipboard/clipboard.min.js"></script>
<script src="RegressionLab_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="RegressionLab_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="RegressionLab_files/libs/quarto-html/popper.min.js"></script>
<script src="RegressionLab_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="RegressionLab_files/libs/quarto-html/anchor.min.js"></script>
<link href="RegressionLab_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="RegressionLab_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="RegressionLab_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="RegressionLab_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="RegressionLab_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup-the-data" id="toc-setup-the-data" class="nav-link active" data-scroll-target="#setup-the-data">Setup: the data</a></li>
  <li><a href="#i.-simple-linear-regression-and-prediction" id="toc-i.-simple-linear-regression-and-prediction" class="nav-link" data-scroll-target="#i.-simple-linear-regression-and-prediction">I. Simple linear regression and prediction</a>
  <ul class="collapse">
  <li><a href="#explore-the-data" id="toc-explore-the-data" class="nav-link" data-scroll-target="#explore-the-data">1. Explore the data</a></li>
  <li><a href="#fit-and-interpret-a-simple-regression" id="toc-fit-and-interpret-a-simple-regression" class="nav-link" data-scroll-target="#fit-and-interpret-a-simple-regression">2. Fit and interpret a simple regression</a></li>
  <li><a href="#prediction-and-model-fit" id="toc-prediction-and-model-fit" class="nav-link" data-scroll-target="#prediction-and-model-fit">3. Prediction and model fit</a></li>
  </ul></li>
  <li><a href="#ii.-controlling-for-a-confound" id="toc-ii.-controlling-for-a-confound" class="nav-link" data-scroll-target="#ii.-controlling-for-a-confound">II. Controlling for a confound</a>
  <ul class="collapse">
  <li><a href="#family-size-with-and-without-frequency" id="toc-family-size-with-and-without-frequency" class="nav-link" data-scroll-target="#family-size-with-and-without-frequency">4. Family size, with and without frequency</a></li>
  </ul></li>
  <li><a href="#iii.-interactions" id="toc-iii.-interactions" class="nav-link" data-scroll-target="#iii.-interactions">III. Interactions</a>
  <ul class="collapse">
  <li><a href="#visualize-the-interaction" id="toc-visualize-the-interaction" class="nav-link" data-scroll-target="#visualize-the-interaction">5. Visualize the interaction</a></li>
  <li><a href="#test-the-interaction" id="toc-test-the-interaction" class="nav-link" data-scroll-target="#test-the-interaction">6. Test the interaction</a></li>
  <li><a href="#interpret-the-interaction" id="toc-interpret-the-interaction" class="nav-link" data-scroll-target="#interpret-the-interaction">7. Interpret the interaction</a></li>
  </ul></li>
  <li><a href="#a-note-on-independence" id="toc-a-note-on-independence" class="nav-link" data-scroll-target="#a-note-on-independence">A note on independence</a></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info">Session info</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Linear Regression Lab</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Arjun Pawar (arjun7@stanford.edu) </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>Note: I tried to adapt most of the code from R to python, but the questions and plots should be mostly the same! I think I was able to reproduce it in python, but if there’s some formatting issues then lmk!</p>
<div id="5d7e6fa8" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="setup-the-data" class="level1">
<h1>Setup: the data</h1>
<p>The data for this lab come from a lexical decision experiment (Baayen et al.&nbsp;2006). Twenty-one participants saw 79 words – the names of animals and plants – and decided as quickly as possible whether each was a real word. We recorded their reaction times (log-transformed, in the <code>RT</code> column).</p>
<p>The reaction times are stored in <code>lexdec_wide.csv</code> in <em>wide</em> format (one column per word). Word-level properties – frequency, morphological family size, length, and class – live in <code>wordinfo.csv</code>. The chunk below reshapes the reaction times into <em>long</em> format and joins in the word properties, giving us a single tidy data frame. (You don’t need to change anything here – just run it.)</p>
<div id="2fb06fef" class="cell" data-message="false" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>base_url <span class="op">=</span> (</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"https://raw.githubusercontent.com/SocialInteractionLab/"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LINGUIST245B/refs/heads/master/assets/data/"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>df_lexdec_wide <span class="op">=</span> pd.read_csv(base_url <span class="op">+</span> <span class="st">"lexdec_wide.csv"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>df_wordinfo <span class="op">=</span> pd.read_csv(base_url <span class="op">+</span> <span class="st">"wordinfo.csv"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>df_lexdec <span class="op">=</span> (</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    df_lexdec_wide</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    .melt(</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        id_vars<span class="op">=</span>[<span class="st">"Subject"</span>, <span class="st">"Sex"</span>, <span class="st">"NativeLanguage"</span>],</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>        var_name<span class="op">=</span><span class="st">"Word"</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>        value_name<span class="op">=</span><span class="st">"RT"</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    .merge(df_wordinfo, on<span class="op">=</span><span class="st">"Word"</span>, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    .rename(columns<span class="op">=</span><span class="kw">lambda</span> x: x.lower().replace(<span class="st">" "</span>, <span class="st">"_"</span>))</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    .rename(columns<span class="op">=</span>{<span class="st">"length"</span>: <span class="st">"word_length"</span>})</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>df_lexdec.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">subject</th>
<th data-quarto-table-cell-role="th">sex</th>
<th data-quarto-table-cell-role="th">nativelanguage</th>
<th data-quarto-table-cell-role="th">word</th>
<th data-quarto-table-cell-role="th">rt</th>
<th data-quarto-table-cell-role="th">frequency</th>
<th data-quarto-table-cell-role="th">familysize</th>
<th data-quarto-table-cell-role="th">word_length</th>
<th data-quarto-table-cell-role="th">class</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>A1</td>
<td>F</td>
<td>English</td>
<td>almond</td>
<td>6.184149</td>
<td>4.204693</td>
<td>0.0</td>
<td>6</td>
<td>plant</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>A2</td>
<td>M</td>
<td>English</td>
<td>almond</td>
<td>6.315358</td>
<td>4.204693</td>
<td>0.0</td>
<td>6</td>
<td>plant</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>A3</td>
<td>F</td>
<td>Other</td>
<td>almond</td>
<td>7.044033</td>
<td>4.204693</td>
<td>0.0</td>
<td>6</td>
<td>plant</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>C</td>
<td>F</td>
<td>English</td>
<td>almond</td>
<td>6.440947</td>
<td>4.204693</td>
<td>0.0</td>
<td>6</td>
<td>plant</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>D</td>
<td>M</td>
<td>Other</td>
<td>almond</td>
<td>6.415097</td>
<td>4.204693</td>
<td>0.0</td>
<td>6</td>
<td>plant</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="i.-simple-linear-regression-and-prediction" class="level1">
<h1>I. Simple linear regression and prediction</h1>
<section id="explore-the-data" class="level2">
<h2 class="anchored" data-anchor-id="explore-the-data">1. Explore the data</h2>
<p>The plot below shows all pairwise relationships among the numeric variables. (You don’t need to change this chunk.)</p>
<div id="907c9ea6" class="cell" data-message="false" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sns.pairplot(df_lexdec[[<span class="st">'rt'</span>, <span class="st">'frequency'</span>, <span class="st">'familysize'</span>, <span class="st">'word_length'</span>]])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="RegressionLab_files/figure-html/cell-4-output-1.png" width="947" height="947" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Looking at the plot, briefly describe one relationship that stands out to you.</p>
<blockquote class="blockquote">
<p>YOUR ANSWER HERE: Looking at the scatterplot between rt and familysize, I could see the dots following somewhat of a trajectory that is a linear pattern. At family size 0 there is some overcrowding of points in a vertical line but the rest follow a linear trend.</p>
</blockquote>
</section>
<section id="fit-and-interpret-a-simple-regression" class="level2">
<h2 class="anchored" data-anchor-id="fit-and-interpret-a-simple-regression">2. Fit and interpret a simple regression</h2>
<p>You want to test the relationship between a word’s frequency (<code>frequency</code>) and how quickly people recognize it (<code>rt</code>).</p>
<p><strong>a)</strong> Make a scatterplot of <code>rt</code> (y-axis) against <code>frequency</code> (x-axis) with point transparency 0.2, and save it to an object called <code>plot.rt_frequency</code>. The last line of the chunk displays it.</p>
<div id="05e97b3f" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>plot_rt_frequency, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>ax.scatter(df_lexdec[<span class="st">'frequency'</span>], df_lexdec[<span class="st">'rt'</span>], alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'frequency'</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'rt'</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="RegressionLab_files/figure-html/cell-5-output-1.png" width="672" height="503" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>b)</strong> Fit a linear regression predicting <code>rt</code> from <code>frequency</code>, and look at the model summary.</p>
<div id="97f28521" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">'rt ~ frequency'</span>, data<span class="op">=</span>df_lexdec).fit()</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>df_lexdec, x<span class="op">=</span><span class="st">'frequency'</span>, y<span class="op">=</span><span class="st">'rt'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>, ax<span class="op">=</span>ax)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>sns.regplot(data<span class="op">=</span>df_lexdec, x<span class="op">=</span><span class="st">'frequency'</span>, y<span class="op">=</span><span class="st">'rt'</span>, </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>            scatter<span class="op">=</span><span class="va">False</span>, color<span class="op">=</span><span class="st">'blue'</span>, ax<span class="op">=</span>ax)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     rt   R-squared:                       0.051
Model:                            OLS   Adj. R-squared:                  0.051
Method:                 Least Squares   F-statistic:                     89.47
Date:                Fri, 15 May 2026   Prob (F-statistic):           1.03e-20
Time:                        22:16:40   Log-Likelihood:                 47.289
No. Observations:                1659   AIC:                            -90.58
Df Residuals:                    1657   BIC:                            -79.75
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.5888      0.022    295.515      0.000       6.545       6.633
frequency     -0.0429      0.005     -9.459      0.000      -0.052      -0.034
==============================================================================
Omnibus:                      222.224   Durbin-Watson:                   1.731
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              348.635
Skew:                           0.921   Prob(JB):                     1.97e-76
Kurtosis:                       4.286   Cond. No.                         19.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="RegressionLab_files/figure-html/cell-6-output-2.png" width="672" height="503" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>c)</strong> Is frequency a significant predictor of reaction time? What is the r-squared value, and what does it tell you about the model?</p>
<blockquote class="blockquote">
<p>YOUR ANSWER HERE: Yes, frequency is a significant predictor here with p-values less than 0.001. The r2 value is 0.051 and this means there is somewhat of a positive linear relationship which is significant.</p>
</blockquote>
</section>
<section id="prediction-and-model-fit" class="level2">
<h2 class="anchored" data-anchor-id="prediction-and-model-fit">3. Prediction and model fit</h2>
<p><strong>a)</strong> Use your model to predict <code>rt</code> for every row, storing the result in a new <code>predictions</code> column of <code>df.lexdec</code>.</p>
<blockquote class="blockquote">
<p>Hint: take a look at the <code>predict()</code> function.</p>
</blockquote>
<div id="638d77f6" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df_lexdec[<span class="st">'predictions'</span>] <span class="op">=</span> model.predict(df_lexdec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The chunk below overlays those predictions (red) on the observed data, with black segments showing the residuals – the gap between each observed and predicted value. (You don’t need to change this chunk.)</p>
<div id="473d53a3" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Original scatter plot</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>ax.scatter(df_lexdec[<span class="st">'frequency'</span>], df_lexdec[<span class="st">'rt'</span>], alpha<span class="op">=</span><span class="fl">0.2</span>, label<span class="op">=</span><span class="st">'Observed'</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Add residual segments as vertical lines</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>ax.vlines(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>df_lexdec[<span class="st">'frequency'</span>],</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    ymin<span class="op">=</span>df_lexdec[[<span class="st">'rt'</span>, <span class="st">'predictions'</span>]].<span class="bu">min</span>(axis<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    ymax<span class="op">=</span>df_lexdec[[<span class="st">'rt'</span>, <span class="st">'predictions'</span>]].<span class="bu">max</span>(axis<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">'black'</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.3</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="fl">0.5</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Add predictions (red points)</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>ax.scatter(df_lexdec[<span class="st">'frequency'</span>], df_lexdec[<span class="st">'predictions'</span>], </span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>           color<span class="op">=</span><span class="st">'red'</span>, alpha<span class="op">=</span><span class="fl">0.8</span>, s<span class="op">=</span><span class="dv">10</span>, label<span class="op">=</span><span class="st">'Predictions'</span>)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'frequency'</span>)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'rt'</span>)</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="RegressionLab_files/figure-html/cell-8-output-1.png" width="672" height="503" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Squaring and summing those residuals gives the <em>residual</em> sum of squares; comparing it to the <em>total</em> sum of squares gives r-squared. The function below computes it (you don’t need to change it):</p>
<div id="4c05add3" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> r_squared(Y_true, Y_pred):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    ss_residual <span class="op">=</span> np.<span class="bu">sum</span>((Y_true <span class="op">-</span> Y_pred)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    ss_total <span class="op">=</span> np.<span class="bu">sum</span>((Y_true <span class="op">-</span> np.mean(Y_true))<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">1</span> <span class="op">-</span> ss_residual <span class="op">/</span> ss_total</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>b)</strong> Use <code>r_squared()</code> to compute r-squared for your predictions, and confirm it matches the value reported by <code>summary()</code> in 2b.</p>
<div id="ec096008" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">### CODE HERE</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> r_squared(df_lexdec[<span class="st">'rt'</span>], df_lexdec[<span class="st">'predictions'</span>])</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R-squared: </span><span class="sc">{</span>r2<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>R-squared: 0.05122788018895541</code></pre>
</div>
</div>
<p><strong>c)</strong> In theory, what are the minimum and maximum values r-squared can take on <strong>training data</strong> with a linear regression, and why? What does an r-squared of 0 mean?</p>
<blockquote class="blockquote">
<p>YOUR ANSWER HERE: The range of r2 values can be from 0 to 1 depending on the strength of the correlation i.e.&nbsp;how well our predictions fit the data based on sum of squares of residuals. An r2 value of 0 means there is no linear relationship between the data and the predictions because the sum of squares of residuals equals the sum of squares between the data and the mean.</p>
</blockquote>
</section>
</section>
<section id="ii.-controlling-for-a-confound" class="level1">
<h1>II. Controlling for a confound</h1>
<p>In psycholinguistics, as in much of psychology, people often run regressions to assess the relationship between two variables while “controlling” for others. But which variables we control for is a substantive decision. Here we’ll see what controlling for a variable can do.</p>
<p>A word’s <strong>morphological family size</strong> (<code>family_size</code>) is the number of morphologically related words – derived forms and compounds – it belongs to (log-transformed).</p>
<section id="family-size-with-and-without-frequency" class="level2">
<h2 class="anchored" data-anchor-id="family-size-with-and-without-frequency">4. Family size, with and without frequency</h2>
<p><strong>a)</strong> Fit a simple linear regression predicting <code>rt</code> from <code>family_size</code> and look at the summary. Is family size a significant predictor of reaction time? Briefly, what do the intercept and slope mean?</p>
<div id="667df185" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>model_family <span class="op">=</span> smf.ols(<span class="st">'rt ~ familysize'</span>, data<span class="op">=</span>df_lexdec).fit()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_family.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     rt   R-squared:                       0.035
Model:                            OLS   Adj. R-squared:                  0.035
Method:                 Least Squares   F-statistic:                     60.90
Date:                Fri, 15 May 2026   Prob (F-statistic):           1.06e-14
Time:                        22:16:41   Log-Likelihood:                 33.607
No. Observations:                1659   AIC:                            -63.21
Df Residuals:                    1657   BIC:                            -52.39
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.4218      0.007    857.823      0.000       6.407       6.436
familysize    -0.0522      0.007     -7.804      0.000      -0.065      -0.039
==============================================================================
Omnibus:                      225.988   Durbin-Watson:                   1.710
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              355.641
Skew:                           0.933   Prob(JB):                     5.94e-78
Kurtosis:                       4.291   Cond. No.                         2.11
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>YOUR ANSWER HERE: Yes, the results show that it is a significant relationship. The slope is -0.0522 which means that for every one unit increase in family size, the reaction time decreases by 0.0522 units (ms). The intercept is 6.4218 which means that when family size is 0, the reaction time is 6.4218 on average.</p>
</blockquote>
<p>Morphological family size is strongly correlated with word frequency – words with big families also tend to be high-frequency – and frequency is itself a powerful predictor of recognition speed.</p>
<p><strong>b)</strong> Now fit a regression predicting <code>rt</code> from BOTH <code>family_size</code> and <code>frequency</code>. Is family size still a significant predictor? What could explain the change, if there is one?</p>
<div id="11dad61f" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>model_both <span class="op">=</span> smf.ols(<span class="st">'rt ~ familysize + frequency'</span>, data<span class="op">=</span>df_lexdec).fit()</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_both.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     rt   R-squared:                       0.053
Model:                            OLS   Adj. R-squared:                  0.052
Method:                 Least Squares   F-statistic:                     46.17
Date:                Fri, 15 May 2026   Prob (F-statistic):           3.06e-20
Time:                        22:16:41   Log-Likelihood:                 48.683
No. Observations:                1659   AIC:                            -91.37
Df Residuals:                    1656   BIC:                            -75.12
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.5639      0.027    244.685      0.000       6.511       6.616
familysize    -0.0157      0.009     -1.669      0.095      -0.034       0.003
frequency     -0.0353      0.006     -5.511      0.000      -0.048      -0.023
==============================================================================
Omnibus:                      219.679   Durbin-Watson:                   1.734
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              342.490
Skew:                           0.915   Prob(JB):                     4.26e-75
Kurtosis:                       4.268   Cond. No.                         24.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>YOUR ANSWER HERE: The family size variable is no longer significant here with p-values much greater now (&gt;0.05). This means that the relationship between family size and reaction time is not significant when we control for frequency. The previous effects could be due to the fact that frequency and family size are strongly correlated with each other and not individually significant.</p>
</blockquote>
</section>
</section>
<section id="iii.-interactions" class="level1">
<h1>III. Interactions</h1>
<p>So far we’ve treated the frequency effect as if it were the same for every reader. But the speed-up that frequency buys might depend on who is reading. In this section we’ll ask whether the effect of <code>frequency</code> on <code>rt</code> is <em>moderated</em> by a participant’s language background (<code>native_language</code>: <code>English</code> vs.&nbsp;<code>Other</code>).</p>
<section id="visualize-the-interaction" class="level2">
<h2 class="anchored" data-anchor-id="visualize-the-interaction">5. Visualize the interaction</h2>
<p>Make a scatterplot of <code>rt</code> against <code>frequency</code>, add a linear regression line, and facet by <code>native_language</code>.</p>
<blockquote class="blockquote">
<p>Hint: <code>geom_smooth(method = "lm")</code> and <code>facet_wrap()</code>.</p>
</blockquote>
<div id="1d62ab4e" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> sns.lmplot(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>df_lexdec,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">'frequency'</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">'rt'</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    col<span class="op">=</span><span class="st">'nativelanguage'</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    scatter_kws<span class="op">=</span>{<span class="st">'alpha'</span>: <span class="fl">0.2</span>},</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    aspect<span class="op">=</span><span class="fl">1.2</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="RegressionLab_files/figure-html/cell-13-output-1.png" width="1142" height="470" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Another way to see the same thing is to chop <code>frequency</code> into thirds (terciles) and compare language groups within each. The chunk below builds the terciles and plots them (you don’t need to change it):</p>
<div id="32fabe46" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cut_terciles(x):</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.cut(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>        x,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>        bins<span class="op">=</span>x.quantile([<span class="dv">0</span>, <span class="dv">1</span><span class="op">/</span><span class="dv">3</span>, <span class="dv">2</span><span class="op">/</span><span class="dv">3</span>, <span class="dv">1</span>]),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        include_lowest<span class="op">=</span><span class="va">True</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Add frequency_terciles column</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>df_lexdec[<span class="st">'frequency_terciles'</span>] <span class="op">=</span> cut_terciles(df_lexdec[<span class="st">'frequency'</span>])</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> sns.catplot(</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>df_lexdec,</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">'nativelanguage'</span>,</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">'rt'</span>,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    hue<span class="op">=</span><span class="st">'frequency_terciles'</span>,</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    col<span class="op">=</span><span class="st">'frequency_terciles'</span>,</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    kind<span class="op">=</span><span class="st">'box'</span>,</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>    aspect<span class="op">=</span><span class="fl">0.8</span>,</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>    palette<span class="op">=</span><span class="st">'Set2'</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="RegressionLab_files/figure-html/cell-14-output-1.png" width="1174" height="374" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="test-the-interaction" class="level2">
<h2 class="anchored" data-anchor-id="test-the-interaction">6. Test the interaction</h2>
<p>Fit two linear models with <code>rt</code> as the outcome: one with <code>frequency</code> and <code>native_language</code> but <strong>no</strong> interaction, and one that <strong>adds</strong> their interaction. Compare the two models with <code>anova()</code>.</p>
<div id="2aed9473" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.anova <span class="im">import</span> anova_lm</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>model_no_interaction <span class="op">=</span> smf.ols(<span class="st">'rt ~ frequency + nativelanguage'</span>, data<span class="op">=</span>df_lexdec).fit()</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>model_with_interaction <span class="op">=</span> smf.ols(<span class="st">'rt ~ frequency * nativelanguage'</span>, data<span class="op">=</span>df_lexdec).fit()</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>anova_results <span class="op">=</span> anova_lm(model_no_interaction, model_with_interaction)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(anova_results)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   df_resid        ssr  df_diff   ss_diff          F    Pr(&gt;F)
0    1656.0  81.886834      0.0       NaN        NaN       NaN
1    1655.0  81.388664      1.0  0.498171  10.130067  0.001486</code></pre>
</div>
</div>
<p>Is the interaction term doing real work? How does that match what you saw in the plots in Problem 5?</p>
<blockquote class="blockquote">
<p>YOUR ANSWER HERE: The interaction term seems important here as the anova comparison gave us significant results. From the plots, we could see different slopes (visually) and the box plots had gaps which changed in magnitude across levels.</p>
</blockquote>
</section>
<section id="interpret-the-interaction" class="level2">
<h2 class="anchored" data-anchor-id="interpret-the-interaction">7. Interpret the interaction</h2>
<p><code>native_language</code> is already binary, so we can make an explicit 0/1 dummy variable: 0 for native English speakers, 1 otherwise. The chunk below builds it and fits the interaction model (you don’t need to change it):</p>
<div id="41f77dde" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df_lexdec[<span class="st">'nonnative'</span>] <span class="op">=</span> (df_lexdec[<span class="st">'nativelanguage'</span>] <span class="op">==</span> <span class="st">'Other'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>interaction_model <span class="op">=</span> smf.ols(<span class="st">'rt ~ frequency + nonnative + nonnative:frequency'</span>, </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                            data<span class="op">=</span>df_lexdec).fit()</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(interaction_model.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     rt   R-squared:                       0.158
Model:                            OLS   Adj. R-squared:                  0.157
Method:                 Least Squares   F-statistic:                     103.8
Date:                Fri, 15 May 2026   Prob (F-statistic):           1.39e-61
Time:                        22:16:41   Log-Likelihood:                 146.70
No. Observations:                1659   AIC:                            -285.4
Df Residuals:                    1655   BIC:                            -263.8
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
=======================================================================================
                          coef    std err          t      P&gt;|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               6.4661      0.028    232.626      0.000       6.412       6.521
frequency              -0.0311      0.006     -5.504      0.000      -0.042      -0.020
nonnative               0.2863      0.042      6.744      0.000       0.203       0.370
nonnative:frequency    -0.0275      0.009     -3.183      0.001      -0.044      -0.011
==============================================================================
Omnibus:                      185.853   Durbin-Watson:                   1.535
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              292.502
Skew:                           0.789   Prob(JB):                     3.05e-64
Kurtosis:                       4.319   Cond. No.                         49.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>The model is:</p>
<p><span class="math display">\[rt_i = \beta_0 + \beta_1 \cdot frequency_i + \beta_2 \cdot nonnative_i + \beta_3 \cdot (nonnative_i \cdot frequency_i) + \epsilon_i\]</span></p>
<p><strong>a)</strong> What does each of <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_2\)</span>, and <span class="math inline">\(\beta_3\)</span> mean substantively – in terms of frequency, reaction time, and language background?</p>
<blockquote class="blockquote">
<p>YOUR ANSWER HERE: <span class="math inline">\(\beta_0\)</span> the intercept predicts rt when frequency and non-native are both 0, <span class="math inline">\(\beta_1\)</span> is the slope of the frequency variable, <span class="math inline">\(\beta_2\)</span> is the slope of the language background variable, and <span class="math inline">\(\beta_3\)</span> is the slope of the interaction term to tell us how much the frequency differs between language backgrounds. Each of these slopes tell us how much rt changes for a one unit change in the respective variable when the other variables are held constant.</p>
</blockquote>
<p><strong>b)</strong> Based on the summary, is there evidence of moderation – does the frequency effect differ by language background? Which coefficient tells you, and which direction does it go?</p>
<blockquote class="blockquote">
<p>YOUR ANSWER HERE: We can see moderation here and frequency effects are different for the different language backgrounds. The interaction coefficient (-0.0275) is significant and is negative meaning that the frequency effect is more negative (higher in magnitude) for non-native speakers (encoded with 1).</p>
</blockquote>
</section>
</section>
<section id="a-note-on-independence" class="level1">
<h1>A note on independence</h1>
<p>Throughout this lab we have fit ordinary linear models with <code>lm()</code>, which assume that every row of the data is an independent observation. That assumption is <strong>not met</strong> here: each of our 21 participants contributed a response to all 79 words, so the rows are clustered both by participant and by word. Next week we will see how <em>mixed-effects models</em> (<code>lmer</code>) let us model that structure directly, instead of pretending it isn’t there.</p>
</section>
<section id="session-info" class="level1">
<h1>Session info</h1>
<pre class="{r}"><code>sessionInfo()</code></pre>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>